services:
  dufs:
    image: sigoden/dufs:latest
    container_name: dufs
    environment:
      - DUFS_AUTH=${DUFS_AUTH}
      - DUFS_ALLOW_ALL=true
    volumes:
      - ${MEDIA_ROOT}/dufs:/data
    expose:
      - 5000
    command: /data
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.dufs.rule=Host(`dufs.${BASE_DOMAIN}`)
      - traefik.http.routers.dufs.entrypoints=web
      - traefik.http.services.dufs.loadbalancer.server.port=5000
      - diun.enable=true
    networks:
      - traefik

networks:
  traefik:
    external: true
