services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=home.${BASE_DOMAIN}
    volumes:
      - ${APPDATA_ROOT}/homepage:/app/config
      - ./docker.yaml:/app/config/docker.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`home.${BASE_DOMAIN}`)"
      - "traefik.http.routers.homepage.entrypoints=web"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      - "diun.enable=true"
    networks:
      - traefik

networks:
  traefik:
    external: true
